package employemanagement;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

public class AdminView extends HttpServlet {
       @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
   
          
          PrintWriter pw=resp.getWriter();
          pw.println("<!DOCTYPE html>\r\n"
          		+ "<html>\r\n"
          		+ "<head>\r\n"
          		+ "<meta charset=\"ISO-8859-1\">\r\n"
          		+ "<title>Login page</title>\r\n"
          		+ " <style>\r\n"
          		+ "	 * {\r\n"
          		+ "      margin: 0;\r\n"
          		+ "      padding: 0;\r\n"
          		+ "      box-sizing: border-box;\r\n"
          		+ "      font-family: 'Poppins', sans-serif;\r\n"
          		+ "    }\r\n"
          		+ "     body {\r\n"
          		+ "      height: 100vh;\r\n"
          		+ "      display: flex;\r\n"
          		+ "      justify-content: center;\r\n"
          		+ "      align-items: center;\r\n"
          		+ "      background: linear-gradient(135deg, #74ABE2, #5563DE);\r\n"
          		+ "    }\r\n"
          		+ "\r\n"
          		+ "    .div {\r\n"
          		+ "      background-color: #ffffff;\r\n"
          		+ "      padding: 40px 60px;\r\n"
          		+ "      border-radius: 20px;\r\n"
          		+ "      box-shadow: 0 10px 25px rgba(0, 0, 0, 0.1);\r\n"
          		+ "      text-align: center;\r\n"
          		+ "      width: 350px;\r\n"
          		+ "    }\r\n"
          		+ "\r\n"
          		+ "    h2 {\r\n"
          		+ "      color: #333;\r\n"
          		+ "      margin-bottom: 25px;\r\n"
          		+ "      font-size: 24px;\r\n"
          		+ "      letter-spacing: 0.5px;\r\n"
          		+ "    }\r\n"
          		+ "\r\n"
          		+ "    input{\r\n"
          		+ "      width: 100%;\r\n"
          		+ "      padding: 12px;\r\n"
          		+ "      margin: 10px 0;\r\n"
          		+ "      border: 2px solid #ddd;\r\n"
          		+ "      border-radius: 8px;\r\n"
          		+ "      font-size: 15px;\r\n"
          		+ "      transition: 0.3s;\r\n"
          		+ "    }\r\n"
          		+ "\r\n"
          		+ "    input:focus {\r\n"
          		+ "      border-color: #5563DE;\r\n"
          		+ "      outline: none;\r\n"
          		+ "      box-shadow: 0 0 8px rgba(85, 99, 222, 0.3);\r\n"
          		+ "    }\r\n"
          		+ "     .btn {\r\n"
          		+ "      width: 100%;\r\n"
          		+ "      padding: 12px;\r\n"
          		+ "      margin-top: 15px;\r\n"
          		+ "      border: none;\r\n"
          		+ "      border-radius: 30px;\r\n"
          		+ "      font-size: 16px;\r\n"
          		+ "      font-weight: 600;\r\n"
          		+ "      cursor: pointer;\r\n"
          		+ "    }\r\n"
          		+ "\r\n"
          		+ "    .login-btn {\r\n"
          		+ "      background: #5563DE;\r\n"
          		+ "      color: #fff;\r\n"
          		+ "    }\r\n"
          		+ "\r\n"
          		+ "    .login-btn:hover {\r\n"
          		+ "      background: #3843b8;\r\n"
          		+ "      transform: scale(1.05);\r\n"
          		+ "      box-shadow: 0 5px 15px rgba(85, 99, 222, 0.4);\r\n"
          		+ "    }\r\n"
          		+ "\r\n"
          		+ "    .create-btn {\r\n"
          		+ "      background: transparent;\r\n"
          		+ "      border: 2px solid #5563DE;\r\n"
          		+ "      color: #5563DE;\r\n"
          		+ "    }\r\n"
          		+ "\r\n"
          		+ "    .create-btn:hover {\r\n"
          		+ "      background: #5563DE;\r\n"
          		+ "      color: #fff;\r\n"
          		+ "    }\r\n"
          		+ "    \r\n"
          		+ " </style>\r\n"
          		+ "</head>\r\n"
          		+ "<body>\r\n"
          		+ "   <div class=\"div\">\r\n"
          		+ "    <h2>Admin Login</h2>\r\n"
          		+ "    <form method=\"post\" action=\"adminlogin\">\r\n"
          		+ "      <input type=\"text\" placeholder=\"Enter Username\" name=\"email\"> \r\n"
          		+ "      <input type=\"password\" placeholder=\"Enter Password\" name=\"password\">\r\n"
          		+ "      \r\n"
          		+ "      <!-- Buttons -->\r\n"
          		+ "      <button type=\"submit\" class=\"btn login-btn\">Submit</button>\r\n"
          		+ "    </form>\r\n"
          		+ "  </div>\r\n"
          		+ "</body>\r\n"
          		+ "</html>");
    }
}
